name: AutoModpack4Paper
version: '${version}'
main: dev.automodpack4paper.AutoModpack4Paper
api-version: '26.2'
description: Unofficial add-on that lets Paper servers work with AutoModpack clients.
website: https://github.com/noushal/AutoModpack4Paper
dependencies:
  server:
    packetevents:
      load: BEFORE
      required: true
      join-classpath: true
